config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts 
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }

  def self.published # class method
    ####some commands to run on the post model
  end

  def next_post #instance method
    ####some commands to run on a single post
  end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter:authenticate_user!,:except=>[:index,:show] #beforefilter
  
  def index 
    @posts = Post.all
  end

  def show #CRUD controller action (posts#show) 
    @post = Post.find(params[:id])#Instance variable
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
 
  if @post.save
  redirect_to @post
else
  render 'new'
end
  end
  
  def update
  @post = Post.find(params[:id])
 
  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end
  
  def destroy
  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to posts_path
end
  

  def post_params # strong parameters
    params.require(:post).permit(:title, :body)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container main-header col-xs-12">
    
    <div class="header-left col-sm-6 col-xs-12">
      <h1 class="blog-title">Yousuf's Blog of the Day</h1>
    </div>
    
    <div class="header-right col-sm-6 col-xs-12">
      <p class="navbar-text text-center">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong></br>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <!--<h3 class="btn btn-primary btn-lg pull-right"><%= link_to 'New Post', new_post_path %></h3>-->
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    
  </div>

<%= yield %>

<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->




</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p class="form-field title-field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p class="text-field body-field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <h3 class="submit-form-button btn btn-primary">
    <%= f.submit %>
  </h3>
 
<% end %>

app/views/posts/edit.html.erb
<div class="container edit-blog col-xs-12">

<h1> Editing Post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="index-post-list col-xs-12">
  <h3 class="new-post btn btn-primary btn-lg"><%= link_to 'New Post', new_post_path %></h3>
  <% @posts.each do |post| %>
    <div class="index-post col-xs-offset-1 col-xs-10">
      <h1 class="post-title"><%= post.title %></h1>
      <h3 class="post-date"><%= post.created_at.to_formatted_s(:long) %></h3>
      <!--<%= post.body %>-->
      <!--<%= post.category_id %>-->
      <!--<%= post.intro %>-->
      <!--<%= post.user_id %>-->
      <button type="button" class="index-button btn btn-default">
        <%= link_to 'Show', post_path(post) %>
      </button>
      <button type="button" class="index-button btn btn-default">
        <%= link_to 'Edit', edit_post_path(post) %>
      </button>
      <button type="button" class="index-button btn btn-default">
        <%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </button>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="new-post col-xs-12">

<h1>New Post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<div class="container show-blog col-xs-12">
    <!--<h2 class="title-title">Title:</h2>-->
    <h1 class="blog-title"><%= @post.title %></h1>
    
    <!--<h2 class="show-intro">Intro:</h2>-->
    <h4 class="blog-intro"><%= @post.intro %></h4>
    
    <!--<h2 class="show-body">Body:</h2>-->
    <p class="blog-body"><%= @post.body %></p>
    
    <button class="btn btn-default back-button"><%= link_to 'Back', posts_path %></button>
    <button class="btn btn-default"><%= link_to 'Edit', edit_post_path(@post) %></button>
    
</div>